# A Simple Scikit-Learn Classification Workflow

This notebook shows a breif workflow you might use with `scikit-learn` to build a machine learning model to classify whether or not a patient has heart disease.

It follows the diagram below:

<img src="../images/sklearn-workflow.png"/>

**Note:** This workflow assumes your data is ready to be used with machine learning models (is numerical, has no missing values).

In [17]:
# Standard Imports
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 


## 1. Get The Data Ready

In [18]:
# Import the dataset
heart_disease = pd.read_csv('../datasets/heart-disease.csv')

# View the data
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

With this example, we're going to use all of the columns except the target column to predict the targert column.

In other words, using a patient's medical and demographic data to predict whether or not they have heart disease.

In [19]:
X = heart_disease.drop('target', axis=1)
y = heart_disease['target']

In [20]:
# Split the data into training and test 
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# View shapes of data
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((242, 13), (61, 13), (242,), (61,))

## 2. Choose the model/estimator

You can do this using the [Scikit-Learn machine learning map](https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html).

<img src="../images/sklearn-ml-map.png" width=500/>

In Scikit-Learn, machine learning models are referred to as estimators.

In this case, since we're working on a classification problem, we've chosen the RandomForestClassifier estimator which is part of the ensembles module.

In [23]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=100)

## 3. Fit the Model to the Data and make a prediction

In [24]:
model.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

Once a model has learned patterns in data, you can use them to make a prediction with the `predict()` function.

In [25]:
# Make Predictions 
y_preds = model.predict(X_test)

In [26]:
np.array(y_test)

array([0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1])

In [27]:
# this will be the same format as y_test
y_preds 

array([0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1])

In [32]:
X_test.loc[201]

age          60.0
sex           1.0
cp            0.0
trestbps    125.0
chol        258.0
fbs           0.0
restecg       0.0
thalach     141.0
exang         1.0
oldpeak       2.8
slope         1.0
ca            1.0
thal          3.0
Name: 201, dtype: float64

In [13]:
heart_disease.loc[201]

age          60.0
sex           1.0
cp            0.0
trestbps    125.0
chol        258.0
fbs           0.0
restecg       0.0
thalach     141.0
exang         1.0
oldpeak       2.8
slope         1.0
ca            1.0
thal          3.0
target        0.0
Name: 201, dtype: float64

In [33]:
# Make a prediction on a single sample (has to be array)
model.predict(np.array(X_test.loc[201]).reshape(1, -1))

array([0])

## 4. Evaluate the model
A trained model/estimator can be evaluated by calling the `score()` function and passing it a collection of data.

In [15]:
# On the training set
model.score(X_train, y_train)

1.0

In [16]:
# On the test set(unseen)
model.score(X_test, y_test)

0.8360655737704918

## 5. Experiment to improve (hyperparameter tuning)

A model's first evaluation metrics aren't always its last. One way to improve a models predictions is with hyperparameter tuning.

In [49]:
np.random.seed(42)
for i in range(10, 100, 10):
    print(f"Trying model with {i} estimators...")
    model = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accruacy on test set: {model.score(X_test, y_test)}")
    print("")

Trying model with 10 estimators...
Model accruacy on test set: 0.819672131147541

Trying model with 20 estimators...
Model accruacy on test set: 0.8032786885245902

Trying model with 30 estimators...
Model accruacy on test set: 0.819672131147541

Trying model with 40 estimators...
Model accruacy on test set: 0.8524590163934426

Trying model with 50 estimators...
Model accruacy on test set: 0.9016393442622951

Trying model with 60 estimators...
Model accruacy on test set: 0.8360655737704918

Trying model with 70 estimators...
Model accruacy on test set: 0.8360655737704918

Trying model with 80 estimators...
Model accruacy on test set: 0.8852459016393442

Trying model with 90 estimators...
Model accruacy on test set: 0.8688524590163934



**Note:** It's best practice to test different hyperparameters with a validation set or cross-validation.

In [50]:
from sklearn.model_selection import cross_val_score

# Try different numbers of estimators with cross-validation and no cross-validation
np.random.seed(42)
for i in range(10, 100, 10):
    print(f"Trying model with {i} estimators...")
    model = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accruacy on test set: {model.score(X_test, y_test)}")
    print(f"Cross-validation score: {np.mean(cross_val_score(model, X, y, cv=5)) * 100}%")
    print("")

Trying model with 10 estimators...
Model accruacy on test set: 0.819672131147541
Cross-validation score: 78.53551912568305%

Trying model with 20 estimators...
Model accruacy on test set: 0.8688524590163934
Cross-validation score: 79.84699453551912%

Trying model with 30 estimators...
Model accruacy on test set: 0.8360655737704918
Cross-validation score: 80.50819672131148%

Trying model with 40 estimators...
Model accruacy on test set: 0.8360655737704918
Cross-validation score: 82.15300546448088%

Trying model with 50 estimators...
Model accruacy on test set: 0.8524590163934426
Cross-validation score: 81.1639344262295%

Trying model with 60 estimators...
Model accruacy on test set: 0.8360655737704918
Cross-validation score: 83.47540983606557%

Trying model with 70 estimators...
Model accruacy on test set: 0.8524590163934426
Cross-validation score: 81.83060109289617%

Trying model with 80 estimators...
Model accruacy on test set: 0.8360655737704918
Cross-validation score: 82.81420765027

## 6. Save a model for later use

A trained model can be exported and saved so it can be imported and used later. One way to save a model is using Python's `pickle` module.

In [51]:
import pickle

# Save trained model to file
pickle.dump(model, open("random_forest_model_1.pkl", "wb"))

In [53]:
# Load a saved model and make a prediction on a single example
loaded_model = pickle.load(open("random_forest_model_1.pkl", "rb"))
loaded_model.predict(np.array(X_test.loc[201]).reshape(1, -1))

array([0])