In [1]:
import numpy as np 

## DataTypes & Attributes

In [2]:
## Numpys main datatype is ndarray 
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1,2,3.0,], 
            [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3,],
              [4,5,6],
              [7, 8, 9]],
             [[10, 11, 12],
             [13, 14, 15],
             [16, 17, 18]]])

In [7]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [14]:
a1

array([1, 2, 3])

In [15]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [16]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [13]:
a1.ndim, a2.ndim, a3.ndim #ndim is number of dimensions

(1, 2, 3)

In [17]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [19]:
a1.size, a2.size, a3.size # number of elements in our array

(3, 6, 18)

In [20]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

## Create a DataFrame from Numpy Array 

In [22]:
import pandas as pd 
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5

## 2. Creating Numpy Arrays

In [23]:
sample_array = np.array([1, 2, 3])
sample_array_array

array([1, 2, 3])

In [24]:
sample_array.dtype

dtype('int64')

In [27]:
ones = np.ones((2, 3)) # type shift + tab in ( )
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [29]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [32]:
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[7, 4, 4, 1, 0],
       [2, 3, 2, 4, 3],
       [3, 9, 0, 2, 3]])

In [33]:
random_array.size

15

In [34]:
random_array.shape

(3, 5)

In [35]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.88137349, 0.25342688, 0.26845196],
       [0.25455371, 0.9523817 , 0.4643086 ],
       [0.49881895, 0.94675721, 0.06603867],
       [0.08218753, 0.74078506, 0.85712721],
       [0.55658341, 0.51532712, 0.75457425]])

In [36]:
random_array_2.shape

(5, 3)

In [38]:
random_array_3 = np.random.rand(5, 3) # shift + tab in ( )
random_array_3

array([[0.12365564, 0.51303865, 0.82853222],
       [0.61720944, 0.74918112, 0.03838295],
       [0.35522876, 0.4822571 , 0.93294214],
       [0.41426075, 0.49546537, 0.70806169],
       [0.38170081, 0.33970653, 0.24045339]])

In [56]:
random_array_4 = np.random.random((5, 4))
random_array_4

array([[0.78791812, 0.28956304, 0.06434332, 0.54685513],
       [0.69570852, 0.41641994, 0.68216827, 0.56433112],
       [0.0368542 , 0.84650882, 0.09532694, 0.09354691],
       [0.81255385, 0.66472615, 0.59709773, 0.5195543 ],
       [0.01698404, 0.03944918, 0.7697947 , 0.518483  ]])

In [66]:
# Pseudo-random numbers
np.random.seed(seed=90) # makes the random numbers the same everytime 
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[2, 3, 7],
       [4, 5, 2],
       [0, 3, 0],
       [2, 2, 9],
       [0, 0, 8]])

In [60]:
random_array_4.shape

(5, 3)

In [70]:
np.random.seed(7)
random_array_5 = np.random.random((5, 4))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923, 0.72346518],
       [0.97798951, 0.53849587, 0.50112046, 0.07205113],
       [0.26843898, 0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 , 0.90959353],
       [0.21338535, 0.45212396, 0.93120602, 0.02489923]])

## 3. Viewing arrays and matrices 

In [73]:
# finding unique elements in a numpy array 
np.unique(random_array_4)

array([0, 2, 3, 4, 5, 7, 8, 9])

In [74]:
a1 

array([1, 2, 3])

In [75]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [76]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [77]:
a1[0]

1

In [78]:
a2.shape

(2, 3)

In [79]:
a2[0]

array([1., 2., 3.])

In [80]:
a3.shape

(2, 3, 3)

In [81]:
a3[0] # gives back first matrix 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
a2[1]

array([4. , 5. , 6.5])

In [83]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [84]:
a3[:2, :2, :2] #want first two values of each row columns and array

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [87]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[8, 8, 4, 0, 4],
         [1, 7, 4, 9, 0],
         [1, 0, 6, 2, 0],
         [2, 4, 4, 1, 0]],

        [[0, 2, 3, 7, 6],
         [9, 3, 5, 6, 8],
         [6, 7, 3, 8, 5],
         [6, 4, 2, 7, 9]],

        [[6, 8, 6, 1, 0],
         [7, 6, 8, 5, 4],
         [3, 0, 7, 4, 0],
         [8, 5, 0, 7, 5]]],


       [[[1, 5, 9, 4, 1],
         [9, 6, 5, 6, 8],
         [5, 9, 4, 6, 0],
         [6, 2, 3, 1, 6]],

        [[7, 0, 0, 4, 7],
         [0, 2, 9, 6, 1],
         [2, 2, 8, 9, 7],
         [2, 4, 7, 7, 9]],

        [[1, 0, 1, 8, 7],
         [4, 6, 1, 4, 8],
         [7, 3, 3, 6, 4],
         [9, 5, 7, 9, 9]]]])

In [88]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [93]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :4]

array([[[[8, 8, 4, 0],
         [1, 7, 4, 9],
         [1, 0, 6, 2],
         [2, 4, 4, 1]],

        [[0, 2, 3, 7],
         [9, 3, 5, 6],
         [6, 7, 3, 8],
         [6, 4, 2, 7]],

        [[6, 8, 6, 1],
         [7, 6, 8, 5],
         [3, 0, 7, 4],
         [8, 5, 0, 7]]],


       [[[1, 5, 9, 4],
         [9, 6, 5, 6],
         [5, 9, 4, 6],
         [6, 2, 3, 1]],

        [[7, 0, 0, 4],
         [0, 2, 9, 6],
         [2, 2, 8, 9],
         [2, 4, 7, 7]],

        [[1, 0, 1, 8],
         [4, 6, 1, 4],
         [7, 3, 3, 6],
         [9, 5, 7, 9]]]])

## 4. Manipulating & Comparing Arrays

### Arithmetic

In [95]:
a1

array([1, 2, 3])

In [97]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [98]:
a1 + ones

array([2., 3., 4.])

In [99]:
a1 - ones

array([0., 1., 2.])

In [100]:
a1 * ones

array([1., 2., 3.])

In [103]:
a1

array([1, 2, 3])

In [101]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [104]:
a1 * a2

array([[ 1. ,  4. ,  9. ],
       [ 4. , 10. , 19.5]])

In [118]:
# how can you reshape a2 to be compatible with a3? 
# Search: How to reshape numpy array 
# Answer: Nice job Andre
np.reshape(a1,3) * a3

array([[[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]],

       [[10, 22, 36],
        [13, 28, 45],
        [16, 34, 54]]])

In [119]:
a1/ones

array([1., 2., 3.])

In [122]:
 a2 / a1

array([[1.        , 1.        , 1.        ],
       [4.        , 2.5       , 2.16666667]])

In [123]:
# Floor division get's rid of decimals
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [127]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [124]:
a2 ** 2

array([[ 1.  ,  4.  ,  9.  ],
       [16.  , 25.  , 42.25]])

In [126]:
np.square(a2)

array([[ 1.  ,  4.  ,  9.  ],
       [16.  , 25.  , 42.25]])

In [128]:
a1 + ones

array([2., 3., 4.])

In [129]:
np.add(a1, ones)

array([2., 3., 4.])

In [130]:
a1 % 2

array([1, 0, 1])

In [131]:
np.mod(a1,2)

array([1, 0, 1])

In [132]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [133]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])